export class DomainValuesComponent {

    PriceBookItemCategory = [
        { id:"Hardware",name:"Hardware" },
        { id:"Software",name:"Software" },
        /* { id:"CABLE TALK",name:"CABLE TALK" },
        { id:"NETKEY",name:"NetKey" },
        { id:"AVOCENT",name:"AVOCENT" },
        { id:"SECURITY",name:"SECURITY" },
        { id:"TE",name:"TE" },
        { id:"TRANSITION NETWORKS",name:"TRANSITION NETWORKS" },
        { id:"INS",name:"INS" },
        { id:"MONITORS",name:"Monitors" },
        { id:"NETGEAR",name:"NETGEAR" },
        { id:"SPECO",name:"SPECO" },
        { id:"ERICO",name:"ERICO" },
        { id:"CABLETIES",name:"CABLETIES" },
        { id:"B-LINE",name:"B-LINE" },
        { id:"NEXT LEVEL",name:"NEXT LEVEL" },
        { id:"BLACKBOX",name:"BLACKBOX" },
        { id:"APC",name:"APC" },
        { id:"PHONE",name:"Phone" },
        { id:"SPECIAL ITEMS",name:"SPECIAL ITEMS" },
        { id:"CPI",name:"CPI" },
        { id:"BERK-TEK",name:"BERK-TEK" },
        { id:"RFMOTE",name:"RFMOTE" },
        { id:"ADC-KRONE",name:"ADC-KRONE" },
        { id:"BLACK BOX",name:"BLACK BOX" },
        { id:"LEGRAND",name:"Legrand" },
        { id:"ANDREW",name:"ANDREW" },
        { id:"AMO",name:"AMO" },
        { id:"ALLIED TELESIS",name:"ALLIED TELESIS" },
        { id:"UNIPRISE",name:"UNIPRISE" },
        { id:"TRIPP LITE",name:"TRIPP LITE" },
        { id:"VERINT",name:"VERINT" },
        { id:"?",name:"?" },
        { id:"VALCOM",name:"VALCOM" },
        { id:"PHANTOM",name:"PHANTOM" },
        { id:"WIREMOLD",name:"Wiremold" },
        { id:"POWERDSINE",name:"POWERDSINE" },
        { id:"MOHAWK",name:"MOHAWK" },
        { id:"MIDDLE ATLANTIC",name:"MIDDLE ATLANTIC" },
        { id:"SYSTIMAX",name:"SYSTIMAX" },
        { id:"GENERAL",name:"GENERAL" },
        { id:"AMP AMP",name:"AMP AMP" },
        { id:"ELECTRON METAL",name:"ElectRON METAL" },
        { id:"INFRALINK (NEDCO GENERIC)",name:"INFRALINK (Nedco Generic)" },
        { id:"OBERON",name:"Oberon" },
        { id:"ANIXTER",name:"ANIXTER" },
        { id:"GENERIC",name:"GENERIC" },
        { id:"UBIQUITI",name:"UBIQUITI" },
        { id:"TSOC",name:"TSOC" },
        { id:"HUBBELL",name:"HUBBELL" },
        { id:"BELDEN",name:"BELDEN" },
        { id:"DL CUSTOM",name:"DL CUSTOM" },
        { id:"INFINITE",name:"INFINITE" },
        { id:"TRIPPLITE",name:"TRIPPLITE" },
        { id:"LABOR",name:"Labor" },
        { id:"FCI",name:"FCI" },
        { id:"CABINETS/RACKS/MANAGEMENT",name:"CABINETS/RACKS/MANAGEMENT" },
        { id:"ALTRONICS",name:"ALTRONICS" },
        { id:"COMPUTER PLUG",name:"COMPUTER PLUG" },
        { id:"POWERWARE",name:"POWERWARE" },
        { id:"SUPERIOR ESSEX",name:"SUPERIOR ESSEX" },
        { id:"CISCO",name:"CISCO" },
        { id:"CABLOFIL",name:"CABLOFIL" },
        { id:"LIFT",name:"LIFT" },
        { id:"AXIS",name:"AXIS" },
        { id:"TBA",name:"TBA" },
        { id:"PANDUIT",name:"PANDUIT" },
        { id:"CORNING",name:"CORNING" },
        { id:"AMP",name:"AMP" },
        { id:"CABLETALK",name:"CABLETALK" },
        { id:"DVTEL",name:"DVTel" },
        { id:"CABOFIL",name:"CABOFIL" },
        { id:"EQUIPMENT",name:"EQUIPMENT" },
        { id:"TOSC",name:"TOSC" },
        { id:"CONDUIT AND CONNECTORS",name:"Conduit and Connectors" }, */
    ];
}